version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1-node-browsers
    steps:
    - checkout
    - run: php -version
    - run: sudo apt update
    - run: composer install -n --prefer-dist
    - run: google-chrome --version
    - run: xvfb-run java -Dwebdriver.chrome.driver=chromedriver -jar selenium-server-standalone.jar >/dev/null 2>&1 &
    - run: phpunit --configuration phpunit.xml
workflows:
  version: 2
  workflow:
    jobs:
    - build
